name: Accessibility Test

on: [push, pull_request]

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Accessibility Insights Action
      uses: microsoft/accessibility-insights-action@v1
      with:
        scan-url-relative-path: './index.html'
        output-dir: './a11y-reports'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Issues for Accessibility Issues
      id: create-issues
      run: |
        report_file=$(ls ./a11y-reports/*.html | head -n 1)
        if [ -f "$report_file" ]; then
          issues=$(grep -oP '(?<=<li class="issue-description">).*?(?=</li>)' "$report_file")
          for issue in $issues; do
            gh issue create --title "Accessibility Issue" --body "An accessibility issue was found: $issue"
          done
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}