name: Accessibility Insights

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessibility-insights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Accessibility Insights Action
        uses: microsoft/accessibility-insights-action@v1
        with:
          url: 'file://./index.html'
          output-dir: './a11y-reports'

      - name: Create GitHub Issues for Accessibility Issues
        id: create-issues
        run: |
          if [ -f ./a11y-reports/report.json ]; then
            issues=$(jq -r '.results | map(select(.status == "fail")) | .[] | .description' ./a11y-reports/report.json)
            for issue in $issues; do
              gh issue create --title "Accessibility Issue: $issue" --body "An accessibility issue was found: $issue"
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}