name: Accessibility Test

on: [push, pull_request]

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      checks: write  # Added 'checks: write' permission

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Accessibility Insights Action
      uses: microsoft/accessibility-insights-action@v1
      with:
        scan-url-relative-path: './index.html'
        output-dir: './a11y-reports'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Issue for Accessibility Issues
      run: |
        report_file=$(find ./a11y-reports -name '*.html' | head -n 1)
        if [ -z "$report_file" ]; then
          echo "No report file found."
          exit 0
        fi

        # Extract violations from the HTML report using grep
        violations=$(grep -oP '(?<=<li class="issue-description">).*?(?=</li>)' "$report_file")

        if [ -n "$violations" ]; then
          issue_title="Accessibility Issues Found"
          issue_body="The following accessibility issues were found:\n\n$violations"
          # Create a GitHub issue using the API
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               --data "$(jq -n --arg title "$issue_title" --arg body "$issue_body" '{title: $title, body: $body}')" \
               https://api.github.com/repos/${{ github.repository }}/issues
        else
          echo "No accessibility issues found."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
