name: Accessibility Test

on: [push, pull_request]

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Axe Accessibility Linter
      uses: dequelabs/axe-core-github-action@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Specify the directory or files to scan
        directory: './public'
        fail-build: false  # Set to true if you want the build to fail on accessibility issues

    - name: Create GitHub Issues for Accessibility Violations
      uses: yujinyuz/axe-report-to-issue@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        axe-report-json-path: './axe-results.json'  # Path to the Axe results JSON file
