name: Accessibility Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload --account-name accessibilitydemo --auth-mode key -c '$web' -f index.html -n index.html --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Accessibility Insights Action
      uses: microsoft/accessibility-insights-action@v1
      with:
        scan-url-relative-path: './index.html'
        output-dir: './a11y-reports'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Issues for Accessibility Issues
      id: create-issues
      run: |
        if [ -f ./a11y-reports/report.json ]; then
          issues=$(jq -r '.results | map(select(.status == "fail")) | .[] | .description' ./a11y-reports/report.json)
          for issue in $issues; do
            gh issue create --title "Accessibility Issue: $issue" --body "An accessibility issue was found: $issue"
          done
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}