name: WCAG Compliance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axe-linter:
    name: Run Axe Linter
    runs-on: ubuntu-latest

    steps:
      - name: Run Accessibility Insights Action
        uses: microsoft/accessibility-insights-action@v2
        with:
          scan-url-relative-path: './index.html'
          output-dir: './a11y-reports'
          repo-token: ${{ secrets.GITHUB_TOKEN }}