name: WCAG Compliance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axe-linter:
    name: Run Axe Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.AXE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}