name: WCAG Compliance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  axe-linter:
    name: Run Axe Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Axe Linter GitHub Action
      - name: Run Axe Linter
        uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
