name: WCAG Compliance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start HTTP Server
        run: npx http-server -p 8080 &

      - name: Run Accessibility Insights Action
        uses: microsoft/accessibility-insights-action@v2
        with:
          scan-url: 'http://localhost:8080/index.html'
          output-dir: './a11y-reports'
          repo-token: ${{ secrets.GITHUB_TOKEN }}