name: WCAG Compliance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start local server
        run: |
          npx http-server . -p 44523 &
          sleep 5  # Wait for server to be ready

      - name: Run Accessibility Insights Action
        uses: microsoft/accessibility-insights-action@v2
        with:
          scan-url-relative-path: './index.html'
          output-dir: './a11y-reports'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
