name: Accessibility Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start local server
        run: |
          npm install -g serve
          serve -s . -l 5000 &
          sleep 5
      - name: Run pa11y-ci
        uses: pa11y/pa11y-ci-action@v2
        with:
          urls: 'http://localhost:5000/index.html'
