name: Accessibility Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessibility_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run Pa11y on index.html
      id: pa11y
      run: pa11y file://$GITHUB_WORKSPACE/index.html --reporter json > pa11y-report.json

    - name: Create GitHub Issues for Accessibility Problems
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = JSON.parse(fs.readFileSync('pa11y-report.json', 'utf8'));

          if (report && report.length > 0) {
            report.forEach(issue => {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Accessibility issue: ${issue.message}`,
                body: `**Issue:** ${issue.message}\n**Code:** ${issue.code}\n**Selector:** ${issue.selector}\n**Context:** ${issue.context}\n**Type:** ${issue.type}\n**Type Code:** ${issue.typeCode}\n**Help:** ${issue.help}\n**Help URL:** ${issue.helpUrl}`,
                labels: ['accessibility']
              });
            });
          }
