name: Test HTML and Create Issue on Failure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Run HTMLHint on index.html
        id: htmlhint
        run: |
          htmlhint index.html || echo "HTMLHint failed" > htmlhint_failed.txt

      - name: Install GitHub CLI
        if: failure()
        run: sudo apt-get install -y gh

      - name: Create Issue on Failure
        if: failure() && steps.htmlhint.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_BODY="HTML issues detected in index.html:\n\n$(htmlhint index.html)"
          gh issue create --title "HTML Issues in index.html" --body "$ISSUE_BODY" --label "bug"
